#!/usr/bin/env python3
"""
Complete MySQL Migration Script - FINAL VERSION
Consolidates all WMS modules and schema into one comprehensive migration
This is the ONLY MySQL migration file you need - all others are duplicates

Features included:
- User Management with roles and permissions
- GRPO (Goods Receipt Purchase Order) 
- Inventory Transfer with warehouse support
- Pick List Management with SAP B1 integration
- Inventory Counting
- Bin Scanning with barcode support
- QR Code Label printing
- Quality Control Dashboard
- Branch Management
- Complete SAP B1 integration schemas

Run: python mysql_complete_migration_final.py
"""

import os
import sys
import logging
import pymysql
from pymysql.cursors import DictCursor
from werkzeug.security import generate_password_hash
from datetime import datetime

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

class CompleteMySQLMigrationFinal:
    def __init__(self):
        self.connection = None
        
    def get_mysql_config(self):
        """Get MySQL configuration interactively or from environment"""
        print("=== MySQL Configuration ===")
        config = {
            'host': os.getenv('MYSQL_HOST') or input("MySQL Host (localhost): ").strip() or 'localhost',
            'port': int(os.getenv('MYSQL_PORT') or input("MySQL Port (3306): ").strip() or '3306'),
            'user': os.getenv('MYSQL_USER') or input("MySQL Username: ").strip(),
            'password': os.getenv('MYSQL_PASSWORD') or input("MySQL Password: ").strip(),
            'database': os.getenv('MYSQL_DATABASE') or input("Database Name (wms_db_dev): ").strip() or 'wms_db_dev',
            'charset': 'utf8mb4',
            'autocommit': False
        }
        return config
    
    def connect(self, config):
        """Connect to MySQL database"""
        try:
            self.connection = pymysql.connect(
                host=config['host'],
                port=config['port'], 
                user=config['user'],
                password=config['password'],
                database=config['database'],
                charset=config['charset'],
                cursorclass=DictCursor,
                autocommit=config['autocommit']
            )
            logger.info(f"✅ Connected to MySQL: {config['database']} at {config['host']}:{config['port']}")
            return True
        except Exception as e:
            logger.error(f"❌ MySQL connection failed: {e}")
            return False
    
    def execute_query(self, query, params=None):
        """Execute query with error handling"""
        try:
            with self.connection.cursor() as cursor:
                cursor.execute(query, params)
                return cursor.fetchall()
        except Exception as e:
            logger.error(f"❌ Query failed: {e}")
            logger.error(f"Query: {query[:100]}...")
            raise
    
    def table_exists(self, table_name):
        """Check if table exists"""
        query = """
        SELECT COUNT(*) as count 
        FROM information_schema.tables 
        WHERE table_schema = DATABASE() AND table_name = %s
        """
        result = self.execute_query(query, [table_name])
        return result[0]['count'] > 0
    
    def column_exists(self, table_name, column_name):
        """Check if column exists in table"""
        query = """
        SELECT COUNT(*) as count 
        FROM information_schema.columns 
        WHERE table_schema = DATABASE() AND table_name = %s AND column_name = %s
        """
        result = self.execute_query(query, [table_name, column_name])
        return result[0]['count'] > 0
    
    def create_env_file(self, config):
        """Create comprehensive .env file"""
        env_content = f"""# WMS Complete Environment Configuration
# Generated by mysql_complete_migration_final.py on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

# =================================
# DATABASE CONFIGURATION
# =================================
# Primary MySQL Database
DATABASE_URL=mysql+pymysql://{config['user']}:{config['password']}@{config['host']}:{config['port']}/{config['database']}

# MySQL Direct Connection Settings
MYSQL_HOST={config['host']}
MYSQL_PORT={config['port']}
MYSQL_USER={config['user']}
MYSQL_PASSWORD={config['password']}
MYSQL_DATABASE={config['database']}

# PostgreSQL (Replit Cloud Fallback) - Auto-configured by Replit
# DATABASE_URL will be overridden by Replit in cloud environment

# =================================
# APPLICATION SECURITY
# =================================
# Session Secret (CHANGE IN PRODUCTION!)
SESSION_SECRET=WMS-Secret-Key-{datetime.now().strftime('%Y%m%d')}-Change-In-Production

# Flask Configuration
FLASK_ENV=development
FLASK_DEBUG=True

# =================================
# SAP BUSINESS ONE INTEGRATION
# =================================
# SAP B1 Server Configuration
SAP_B1_SERVER=https://192.168.0.142:50000
SAP_B1_USERNAME=manager
SAP_B1_PASSWORD=1422
SAP_B1_COMPANY_DB=EINV-TESTDB-LIVE-HUST

# SAP B1 Connection Timeout (seconds)
SAP_B1_TIMEOUT=30
SAP_B1_VERIFY_SSL=false

# =================================
# WAREHOUSE MANAGEMENT SETTINGS
# =================================
# Default warehouse codes
DEFAULT_WAREHOUSE=01
DEFAULT_BIN_LOCATION=01-A01-001

# Barcode/QR Code Settings
BARCODE_FORMAT=CODE128
QR_CODE_SIZE=10
LABEL_PRINTER_IP=192.168.1.100

# =================================
# EMAIL CONFIGURATION (Optional)
# =================================
MAIL_SERVER=smtp.gmail.com
MAIL_PORT=587
MAIL_USE_TLS=true
MAIL_USERNAME=your-email@company.com
MAIL_PASSWORD=your-app-password

# =================================
# LOGGING CONFIGURATION
# =================================
LOG_LEVEL=INFO
LOG_FILE=logs/wms.log

# =================================
# BACKUP CONFIGURATION
# =================================
BACKUP_RETENTION_DAYS=30
AUTO_BACKUP_ENABLED=true
BACKUP_PATH=backups/
"""
        
        try:
            with open('.env', 'w') as f:
                f.write(env_content)
            logger.info("✅ Created comprehensive .env file")
            return True
        except Exception as e:
            logger.error(f"❌ Failed to create .env file: {e}")
            return False
    
    def create_all_tables(self):
        """Create all WMS tables in correct order (dependencies first)"""
        
        # 1. Users table (no dependencies)
        if not self.table_exists('users'):
            logger.info("Creating users table...")
            self.execute_query("""
                CREATE TABLE users (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    username VARCHAR(80) UNIQUE NOT NULL,
                    email VARCHAR(120) UNIQUE NOT NULL,
                    password_hash VARCHAR(256) NOT NULL,
                    first_name VARCHAR(80),
                    last_name VARCHAR(80),
                    role VARCHAR(20) NOT NULL DEFAULT 'user',
                    branch_id VARCHAR(10),
                    branch_name VARCHAR(100),
                    default_branch_id VARCHAR(10),
                    user_is_active BOOLEAN DEFAULT TRUE,
                    must_change_password BOOLEAN DEFAULT FALSE,
                    last_login DATETIME,
                    permissions TEXT,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    INDEX idx_username (username),
                    INDEX idx_role (role),
                    INDEX idx_branch (branch_id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            """)
            logger.info("✅ Users table created")
        
        # 2. Branches table (no dependencies) 
        if not self.table_exists('branches'):
            logger.info("Creating branches table...")
            self.execute_query("""
                CREATE TABLE branches (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    branch_code VARCHAR(10) UNIQUE NOT NULL,
                    branch_name VARCHAR(100) NOT NULL,
                    address VARCHAR(255),
                    city VARCHAR(50),
                    state VARCHAR(50),
                    postal_code VARCHAR(20),
                    country VARCHAR(50),
                    phone VARCHAR(20),
                    email VARCHAR(120),
                    manager_name VARCHAR(100),
                    is_active BOOLEAN DEFAULT TRUE,
                    warehouse_codes TEXT,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    INDEX idx_branch_code (branch_code),
                    INDEX idx_active (is_active)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            """)
            logger.info("✅ Branches table created")
        
        # 3. GRPO Documents (depends on users)
        if not self.table_exists('grpo_documents'):
            logger.info("Creating grpo_documents table...")
            self.execute_query("""
                CREATE TABLE grpo_documents (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    grpo_number VARCHAR(50) UNIQUE NOT NULL,
                    po_number VARCHAR(50),
                    vendor_code VARCHAR(50),
                    vendor_name VARCHAR(100),
                    document_date DATE,
                    posting_date DATE,
                    due_date DATE,
                    total_amount DECIMAL(15,2),
                    currency VARCHAR(10) DEFAULT 'USD',
                    status VARCHAR(20) DEFAULT 'draft',
                    warehouse_code VARCHAR(10),
                    branch_id VARCHAR(10),
                    user_id INT,
                    sap_doc_entry INT,
                    sap_doc_num VARCHAR(20),
                    remarks TEXT,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
                    INDEX idx_grpo_number (grpo_number),
                    INDEX idx_po_number (po_number),
                    INDEX idx_vendor (vendor_code),
                    INDEX idx_status (status),
                    INDEX idx_warehouse (warehouse_code),
                    INDEX idx_sap_doc (sap_doc_entry)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            """)
            logger.info("✅ GRPO documents table created")
        
        # 4. GRPO Line Items (depends on grpo_documents)
        if not self.table_exists('grpo_line_items'):
            logger.info("Creating grpo_line_items table...")
            self.execute_query("""
                CREATE TABLE grpo_line_items (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    grpo_id INT NOT NULL,
                    line_number INT NOT NULL,
                    item_code VARCHAR(50),
                    item_description TEXT,
                    quantity DECIMAL(15,3),
                    received_quantity DECIMAL(15,3) DEFAULT 0,
                    unit_price DECIMAL(15,4),
                    line_total DECIMAL(15,2),
                    warehouse_code VARCHAR(10),
                    bin_location VARCHAR(50),
                    batch_number VARCHAR(50),
                    serial_numbers TEXT,
                    expiry_date DATE,
                    manufacturing_date DATE,
                    quality_status VARCHAR(20) DEFAULT 'pending',
                    remarks TEXT,
                    sap_line_num INT,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    FOREIGN KEY (grpo_id) REFERENCES grpo_documents(id) ON DELETE CASCADE,
                    INDEX idx_grpo_line (grpo_id, line_number),
                    INDEX idx_item_code (item_code),
                    INDEX idx_warehouse_bin (warehouse_code, bin_location),
                    INDEX idx_batch (batch_number),
                    INDEX idx_quality (quality_status)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            """)
            logger.info("✅ GRPO line items table created")
        
        # 5. Inventory Transfer Documents (depends on users)
        if not self.table_exists('inventory_transfer_documents'):
            logger.info("Creating inventory_transfer_documents table...")
            self.execute_query("""
                CREATE TABLE inventory_transfer_documents (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    transfer_number VARCHAR(50) UNIQUE NOT NULL,
                    from_warehouse VARCHAR(10),
                    to_warehouse VARCHAR(10),
                    transfer_date DATE,
                    posting_date DATE,
                    status VARCHAR(20) DEFAULT 'draft',
                    total_items INT DEFAULT 0,
                    transferred_items INT DEFAULT 0,
                    user_id INT,
                    approved_by_id INT,
                    approved_at DATETIME,
                    sap_doc_entry INT,
                    sap_doc_num VARCHAR(20),
                    remarks TEXT,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
                    FOREIGN KEY (approved_by_id) REFERENCES users(id) ON DELETE SET NULL,
                    INDEX idx_transfer_number (transfer_number),
                    INDEX idx_warehouses (from_warehouse, to_warehouse),
                    INDEX idx_status (status),
                    INDEX idx_transfer_date (transfer_date),
                    INDEX idx_sap_doc (sap_doc_entry)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            """)
            logger.info("✅ Inventory transfer documents table created")
        
        # 6. Inventory Transfer Line Items (depends on inventory_transfer_documents)
        if not self.table_exists('inventory_transfer_line_items'):
            logger.info("Creating inventory_transfer_line_items table...")
            self.execute_query("""
                CREATE TABLE inventory_transfer_line_items (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    transfer_id INT NOT NULL,
                    line_number INT NOT NULL,
                    item_code VARCHAR(50),
                    item_description TEXT,
                    quantity DECIMAL(15,3),
                    transferred_quantity DECIMAL(15,3) DEFAULT 0,
                    from_warehouse VARCHAR(10),
                    to_warehouse VARCHAR(10),
                    from_bin_location VARCHAR(50),
                    to_bin_location VARCHAR(50),
                    batch_number VARCHAR(50),
                    serial_numbers TEXT,
                    expiry_date DATE,
                    manufacturing_date DATE,
                    unit_cost DECIMAL(15,4),
                    line_total DECIMAL(15,2),
                    status VARCHAR(20) DEFAULT 'pending',
                    remarks TEXT,
                    sap_line_num INT,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    FOREIGN KEY (transfer_id) REFERENCES inventory_transfer_documents(id) ON DELETE CASCADE,
                    INDEX idx_transfer_line (transfer_id, line_number),
                    INDEX idx_item_code (item_code),
                    INDEX idx_warehouses (from_warehouse, to_warehouse),
                    INDEX idx_bins (from_bin_location, to_bin_location),
                    INDEX idx_batch (batch_number),
                    INDEX idx_status (status)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            """)
            logger.info("✅ Inventory transfer line items table created")
        
        # 7. Pick Lists (depends on users) - SAP B1 Compatible
        if not self.table_exists('pick_lists'):
            logger.info("Creating pick_lists table...")
            self.execute_query("""
                CREATE TABLE pick_lists (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    absolute_entry INT UNIQUE,
                    name VARCHAR(100),
                    owner_code INT,
                    owner_name VARCHAR(100),
                    pick_date DATE,
                    status VARCHAR(20) DEFAULT 'ps_Open',
                    object_type VARCHAR(10) DEFAULT '156',
                    use_base_units VARCHAR(10) DEFAULT 'tNO',
                    pick_list_number VARCHAR(50),
                    sales_order_number VARCHAR(50),
                    customer_code VARCHAR(50),
                    customer_name VARCHAR(100),
                    warehouse_code VARCHAR(10),
                    priority VARCHAR(20) DEFAULT 'normal',
                    total_items INT DEFAULT 0,
                    picked_items INT DEFAULT 0,
                    user_id INT,
                    approved_by_id INT,
                    approved_at DATETIME,
                    completed_at DATETIME,
                    remarks TEXT,
                    notes TEXT,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
                    FOREIGN KEY (approved_by_id) REFERENCES users(id) ON DELETE SET NULL,
                    INDEX idx_absolute_entry (absolute_entry),
                    INDEX idx_pick_list_number (pick_list_number),
                    INDEX idx_sales_order (sales_order_number),
                    INDEX idx_status (status),
                    INDEX idx_priority (priority),
                    INDEX idx_customer (customer_code),
                    INDEX idx_warehouse (warehouse_code),
                    INDEX idx_pick_date (pick_date)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            """)
            logger.info("✅ Pick lists table created")
        
        # 8. Pick List Lines (depends on pick_lists) - SAP B1 Compatible
        if not self.table_exists('pick_list_lines'):
            logger.info("Creating pick_list_lines table...")
            self.execute_query("""
                CREATE TABLE pick_list_lines (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    pick_list_id INT NOT NULL,
                    absolute_entry INT,
                    line_number INT NOT NULL,
                    order_entry INT,
                    order_row_id INT,
                    item_code VARCHAR(50),
                    item_description TEXT,
                    picked_quantity DECIMAL(15,3) DEFAULT 0,
                    pick_status VARCHAR(20) DEFAULT 'ps_Open',
                    released_quantity DECIMAL(15,3) DEFAULT 0,
                    previously_released_quantity DECIMAL(15,3) DEFAULT 0,
                    base_object_type INT DEFAULT 17,
                    warehouse_code VARCHAR(10),
                    bin_location VARCHAR(50),
                    batch_number VARCHAR(50),
                    serial_numbers TEXT,
                    batch_numbers TEXT,
                    unit_price DECIMAL(15,4),
                    line_total DECIMAL(15,2),
                    remarks TEXT,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    FOREIGN KEY (pick_list_id) REFERENCES pick_lists(id) ON DELETE CASCADE,
                    INDEX idx_pick_list_line (pick_list_id, line_number),
                    INDEX idx_absolute_entry (absolute_entry),
                    INDEX idx_order_entry (order_entry, order_row_id),
                    INDEX idx_item_code (item_code),
                    INDEX idx_pick_status (pick_status),
                    INDEX idx_warehouse_bin (warehouse_code, bin_location),
                    INDEX idx_batch (batch_number)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            """)
            logger.info("✅ Pick list lines table created")
        
        # 9. Pick List Bin Allocations (depends on pick_list_lines) - SAP B1 Compatible
        if not self.table_exists('pick_list_bin_allocations'):
            logger.info("Creating pick_list_bin_allocations table...")
            self.execute_query("""
                CREATE TABLE pick_list_bin_allocations (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    pick_list_line_id INT NOT NULL,
                    bin_abs_entry INT,
                    quantity DECIMAL(15,3),
                    allow_negative_quantity VARCHAR(10) DEFAULT 'tNO',
                    serial_and_batch_numbers_base_line INT DEFAULT 0,
                    base_line_number INT DEFAULT 0,
                    warehouse VARCHAR(20),
                    bin_code VARCHAR(50),
                    batch_number VARCHAR(50),
                    serial_number VARCHAR(50),
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    FOREIGN KEY (pick_list_line_id) REFERENCES pick_list_lines(id) ON DELETE CASCADE,
                    INDEX idx_pick_list_line (pick_list_line_id),
                    INDEX idx_bin_abs_entry (bin_abs_entry),
                    INDEX idx_warehouse_bin (warehouse, bin_code),
                    INDEX idx_batch (batch_number),
                    INDEX idx_serial (serial_number)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            """)
            logger.info("✅ Pick list bin allocations table created")
        
        # 10. Inventory Counting Documents (depends on users)
        if not self.table_exists('inventory_counting_documents'):
            logger.info("Creating inventory_counting_documents table...")
            self.execute_query("""
                CREATE TABLE inventory_counting_documents (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    counting_number VARCHAR(50) UNIQUE NOT NULL,
                    counting_date DATE,
                    warehouse_code VARCHAR(10),
                    counting_type VARCHAR(20) DEFAULT 'full',
                    status VARCHAR(20) DEFAULT 'open',
                    total_items INT DEFAULT 0,
                    counted_items INT DEFAULT 0,
                    variance_items INT DEFAULT 0,
                    user_id INT,
                    approved_by_id INT,
                    approved_at DATETIME,
                    posted_at DATETIME,
                    sap_doc_entry INT,
                    sap_doc_num VARCHAR(20),
                    remarks TEXT,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
                    FOREIGN KEY (approved_by_id) REFERENCES users(id) ON DELETE SET NULL,
                    INDEX idx_counting_number (counting_number),
                    INDEX idx_warehouse (warehouse_code),
                    INDEX idx_status (status),
                    INDEX idx_counting_date (counting_date),
                    INDEX idx_sap_doc (sap_doc_entry)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            """)
            logger.info("✅ Inventory counting documents table created")
        
        # 11. Inventory Counting Line Items (depends on inventory_counting_documents)
        if not self.table_exists('inventory_counting_line_items'):
            logger.info("Creating inventory_counting_line_items table...")
            self.execute_query("""
                CREATE TABLE inventory_counting_line_items (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    counting_id INT NOT NULL,
                    line_number INT NOT NULL,
                    item_code VARCHAR(50),
                    item_description TEXT,
                    warehouse_code VARCHAR(10),
                    bin_location VARCHAR(50),
                    batch_number VARCHAR(50),
                    serial_numbers TEXT,
                    system_quantity DECIMAL(15,3),
                    counted_quantity DECIMAL(15,3),
                    variance_quantity DECIMAL(15,3),
                    unit_cost DECIMAL(15,4),
                    variance_value DECIMAL(15,2),
                    counting_date DATE,
                    counter_user_id INT,
                    remarks TEXT,
                    sap_line_num INT,
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    FOREIGN KEY (counting_id) REFERENCES inventory_counting_documents(id) ON DELETE CASCADE,
                    FOREIGN KEY (counter_user_id) REFERENCES users(id) ON DELETE SET NULL,
                    INDEX idx_counting_line (counting_id, line_number),
                    INDEX idx_item_code (item_code),
                    INDEX idx_warehouse_bin (warehouse_code, bin_location),
                    INDEX idx_batch (batch_number),
                    INDEX idx_variance (variance_quantity)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            """)
            logger.info("✅ Inventory counting line items table created")
        
        # 12. Bin Scanning Logs (depends on users)
        if not self.table_exists('bin_scanning_logs'):
            logger.info("Creating bin_scanning_logs table...")
            self.execute_query("""
                CREATE TABLE bin_scanning_logs (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    bin_code VARCHAR(50) NOT NULL,
                    warehouse_code VARCHAR(10),
                    scan_type VARCHAR(20) DEFAULT 'inquiry',
                    scanned_by_id INT,
                    scan_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
                    items_found INT DEFAULT 0,
                    scan_result TEXT,
                    device_info VARCHAR(100),
                    session_id VARCHAR(50),
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (scanned_by_id) REFERENCES users(id) ON DELETE SET NULL,
                    INDEX idx_bin_code (bin_code),
                    INDEX idx_warehouse (warehouse_code),
                    INDEX idx_scan_timestamp (scan_timestamp),
                    INDEX idx_scanned_by (scanned_by_id),
                    INDEX idx_session (session_id)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            """)
            logger.info("✅ Bin scanning logs table created")
        
        # 13. QR Code Labels (depends on users)
        if not self.table_exists('qr_code_labels'):
            logger.info("Creating qr_code_labels table...")
            self.execute_query("""
                CREATE TABLE qr_code_labels (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    label_number VARCHAR(50) UNIQUE NOT NULL,
                    qr_code_data TEXT NOT NULL,
                    label_type VARCHAR(20) DEFAULT 'item',
                    item_code VARCHAR(50),
                    item_description TEXT,
                    batch_number VARCHAR(50),
                    serial_number VARCHAR(50),
                    warehouse_code VARCHAR(10),
                    bin_location VARCHAR(50),
                    quantity DECIMAL(15,3),
                    unit_of_measure VARCHAR(20),
                    expiry_date DATE,
                    manufacturing_date DATE,
                    print_count INT DEFAULT 0,
                    last_printed_at DATETIME,
                    created_by_id INT,
                    status VARCHAR(20) DEFAULT 'active',
                    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE SET NULL,
                    INDEX idx_label_number (label_number),
                    INDEX idx_item_code (item_code),
                    INDEX idx_batch_serial (batch_number, serial_number),
                    INDEX idx_warehouse_bin (warehouse_code, bin_location),
                    INDEX idx_label_type (label_type),
                    INDEX idx_status (status)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            """)
            logger.info("✅ QR code labels table created")
        
        self.connection.commit()
        logger.info("✅ All tables created successfully!")
        return True
    
    def insert_default_data(self):
        """Insert default admin user and sample data"""
        
        # Check if admin user already exists
        admin_exists = self.execute_query("SELECT COUNT(*) as count FROM users WHERE username = 'admin'")
        if admin_exists[0]['count'] > 0:
            logger.info("Admin user already exists, skipping default data insertion")
            return True
        
        logger.info("Inserting default data...")
        
        # Default admin user
        admin_password_hash = generate_password_hash('admin123')
        self.execute_query("""
            INSERT INTO users (
                username, email, password_hash, first_name, last_name, 
                role, branch_id, branch_name, permissions
            ) VALUES (
                'admin', 'admin@company.com', %s, 'System', 'Administrator',
                'admin', '01', 'Main Branch', 'all'
            )
        """, [admin_password_hash])
        
        # Default manager user
        manager_password_hash = generate_password_hash('manager123')
        self.execute_query("""
            INSERT INTO users (
                username, email, password_hash, first_name, last_name,
                role, branch_id, branch_name, permissions
            ) VALUES (
                'manager', 'manager@company.com', %s, 'Warehouse', 'Manager',
                'manager', '01', 'Main Branch', 'grpo,inventory_transfer,pick_list,inventory_counting,bin_scanning'
            )
        """, [manager_password_hash])
        
        # Default user
        user_password_hash = generate_password_hash('user123')
        self.execute_query("""
            INSERT INTO users (
                username, email, password_hash, first_name, last_name,
                role, branch_id, branch_name, permissions
            ) VALUES (
                'user', 'user@company.com', %s, 'Warehouse', 'User',
                'user', '01', 'Main Branch', 'grpo,inventory_transfer,pick_list,bin_scanning'
            )
        """, [user_password_hash])
        
        # Default QC user
        qc_password_hash = generate_password_hash('qc123')
        self.execute_query("""
            INSERT INTO users (
                username, email, password_hash, first_name, last_name,
                role, branch_id, branch_name, permissions
            ) VALUES (
                'qc', 'qc@company.com', %s, 'Quality', 'Control',
                'qc', '01', 'Main Branch', 'grpo,inventory_counting,qc_dashboard'
            )
        """, [qc_password_hash])
        
        # Default branch
        self.execute_query("""
            INSERT INTO branches (
                branch_code, branch_name, address, city, state, country,
                phone, email, manager_name, warehouse_codes
            ) VALUES (
                '01', 'Main Branch', '123 Warehouse St', 'Business City', 'State', 'Country',
                '+1-555-0123', 'main@company.com', 'Warehouse Manager', '01,02,03'
            )
        """)
        
        self.connection.commit()
        logger.info("✅ Default data inserted successfully!")
        logger.info("")
        logger.info("=== DEFAULT USER ACCOUNTS ===")
        logger.info("Admin:   username='admin'   password='admin123'")
        logger.info("Manager: username='manager' password='manager123'")
        logger.info("User:    username='user'    password='user123'")
        logger.info("QC:      username='qc'      password='qc123'")
        logger.info("")
        return True
    
    def remove_duplicate_migration_files(self):
        """Remove duplicate MySQL migration files"""
        duplicate_files = [
            'mysql_migration.py',
            'mysql_complete_migration.py', 
            'mysql_picklist_migration.py',
            'mysql_qr_code_migration.py',
            'mysql_complete_picklist_migration_august_2025.py',
            'run_mysql_picklist_migration.py',
            'complete_mysql_fix.py',
            'fix_mysql_schema.py',
            'setup_mysql_env.py',
            'sync_mysql_changes.py',
            'qr_code_migration.py',
            'fix_picklist_schema.py'
        ]
        
        removed_count = 0
        for file_name in duplicate_files:
            if os.path.exists(file_name):
                try:
                    os.remove(file_name)
                    logger.info(f"✅ Removed duplicate migration file: {file_name}")
                    removed_count += 1
                except Exception as e:
                    logger.warning(f"⚠️ Could not remove {file_name}: {e}")
        
        if removed_count > 0:
            logger.info(f"✅ Removed {removed_count} duplicate migration files")
        else:
            logger.info("No duplicate migration files found to remove")
        
        return True
    
    def run_migration(self):
        """Run complete migration process"""
        logger.info("=== WMS Complete MySQL Migration - FINAL VERSION ===")
        logger.info("This script consolidates ALL WMS modules into one database")
        logger.info("")
        
        # Get MySQL configuration
        config = self.get_mysql_config()
        
        # Connect to MySQL
        if not self.connect(config):
            return False
        
        try:
            # Create .env file
            if not self.create_env_file(config):
                return False
            
            # Create all tables
            if not self.create_all_tables():
                return False
            
            # Insert default data
            if not self.insert_default_data():
                return False
            
            # Clean up duplicate files
            self.remove_duplicate_migration_files()
            
            logger.info("")
            logger.info("🎉 MIGRATION COMPLETED SUCCESSFULLY! 🎉")
            logger.info("")
            logger.info("Next steps:")
            logger.info("1. Update your application to use the new .env file")
            logger.info("2. Start your Flask application: python main.py")
            logger.info("3. Login with admin/admin123 to begin using WMS")
            logger.info("4. Configure SAP B1 settings in .env file if needed")
            logger.info("")
            logger.info("All duplicate migration files have been removed.")
            logger.info("This file (mysql_complete_migration_final.py) is now your single migration script.")
            
            return True
            
        except Exception as e:
            logger.error(f"❌ Migration failed: {e}")
            return False
        
        finally:
            if self.connection:
                self.connection.close()
                logger.info("MySQL connection closed")

if __name__ == "__main__":
    migration = CompleteMySQLMigrationFinal()
    success = migration.run_migration()
    sys.exit(0 if success else 1)